### PR TITLE
Rewriting annex - interoperability with other programming models

### PR DESCRIPTION
**Pull request by minsii**
This PR rewrites `Annex D - Interoperability with other Programming Models`. It clarifies MPI Interoperability and defines an OpenSHMEM extended API for querying interoperability features. The interoperability with other communication libraries and languages will be addressed in future work.

Related discussion can be found at [ticket-243](https://github.com/openshmem-org/specification/issues/243).

### CODE REVIEW

**Comment by jamesaross** [comment]
This proposal is ambiguous and poorly defined.  It appears more like a discussion of the state of vendor hybrid MPI/OpenSHMEM implementations and workarounds/suggestions to keep code from breaking. Provided advice should include something like "avoid doing this if possible".

Is the proposal to make non-standard/optional extended interfaces (such as `shmemx_query_interoperability`) part of the OpenSHMEM specification?  This is something we haven't seen before.

The OpenSHMEM specification can only strive to be internally consistent without imposing requirements on external interfaces and implementations we can't control.  Hybrid MPI/OpenSHMEM programs seem to be a poor design choice with unnecessary complexity and will likely remain fragile within a single vendor software stack.  And those applications are unlikely portable to other vendor implementations.  At the very least, this proposal requires a platform to support both MPI and OpenSHMEM and then additional restrictions when developing hybrid code.  I don't think it's in the interest of the OpenSHMEM specification to create dependencies on MPI despite the tendency for vendors to support both programming models.

The hybrid MPI/OpenSHMEM interoperability proposal identifies a poorly defined subset of both programming models to be used to guarantee that the code doesn't break (i.e. API call ordering, no MPMD, thread limitations, process mappings, RMA and atomic operations) but the list is not exhaustive.  Future updates to both MPI and OpenSHMEM will likely require revisiting this list for each change.

Also, the commit to `main_spec.tex` shouldn't be part of the pull request.

**Comment by minsii** [comment]
@jamesaross Thanks for the feedback !

> Is the proposal to make non-standard/optional extended interfaces (such as shmemx_query_interoperability) part of the OpenSHMEM specification? This is something we haven't seen before.

The query API was initially introduced as an extended API because some implementations may not support (or do not want to maintain) the interoperability features. However, the current interface allows such an implementation to simply return 0. Thus, I think it makes more sense to define it as a standard API. I will make the change in the PR.

>The OpenSHMEM specification can only strive to be internally consistent without imposing requirements on external interfaces and implementations we can't control. Hybrid MPI/OpenSHMEM programs seem to be a poor design choice with unnecessary complexity and will likely remain fragile within a single vendor software stack. And those applications are unlikely portable to other vendor implementations. At the very least, this proposal requires a platform to support both MPI and OpenSHMEM and then additional restrictions when developing hybrid code. I don't think it's in the interest of the OpenSHMEM specification to create dependencies on MPI despite the tendency for vendors to support both programming models.

As the OpenSHMEM model focuses on extremely high performance (e.g., a very fast put with int data) whereas MPI focuses on completeness of features (e.g., put with complex datatype), I think some applications are interested in the hybrid model in order to ensure complex algorithms can be easily written with MPI and performance critical routines can be optimized by using OpenSHMEM.

I agree that it is hard to ensure a portable hybrid program as it may rely on non-standard vendor features (e.g., `MPI comm_world rank` == `SHMEM PE`). The goal of this proposal is to help user write portable hybrid code. We are not trying to control the other interfaces (e.g., MPI) or require the vendor to support both models. We are trying to guide user what you should do in your hybrid program to ensure portability, based on the standardized semantics. We also require vendors who support both models to follow standard rules (e.g., support arbitrary order of `shmem/mpi_init` calls). By following this, user should be able to correctly run the hybrid program with any vendor implementations (e.g., using SOS and MVAPICH together).

The second goal of this proposal is to suggest possible optimizations for vendors who support both models (e.g., avoiding unnecessary internal synchronization and making progress for both models).

>The hybrid MPI/OpenSHMEM interoperability proposal identifies a poorly defined subset of both programming models to be used to guarantee that the code doesn't break (i.e. API call ordering, no MPMD, thread limitations, process mappings, RMA and atomic operations) but the list is not exhaustive. Future updates to both MPI and OpenSHMEM will likely require revisiting this list for each change.

We put together the list based on the current OpenSHMEM and MPI specification. It covers the semantics where OpenSHMEM and MPI may overlap. I agree that we may need update for this section if the specification has a major change in future release. But I think it is reasonable.

>Also, the commit to main_spec.tex shouldn't be part of the pull request.

I will fix it.

**Comment by minsii** [comment]
**Notes for 2019-09-10 threads WG meeting:** 

- The last push includes the following major changes:
  1. Replace `shmemx_query_interoperability` with `shmem_query_interoperability`.
  1. Add an example code to demonstrate PE/rank mapping

- PDF version of this PR as on 2019-09-10:
[main_spec.interop.pdf](https://github.com/minsii/openshmem-specification/files/3596886/main_spec.interop.pdf)

- PR #2 is a simplified version that removes the semantics description for `dynamic process` and `RMA models`. This might make more sense from the view of OpenSHMEM users as users unlikely use `OpenSHMEM + MPI dynamic process` or `OpenSHMEM + MPI RMA` together.

- PDF of the simplified version:
[main_spec.interop-simplified.pdf](https://github.com/minsii/openshmem-specification/files/3596899/main_spec.interop-simplified.pdf)

**Comment by minsii** [comment]
**Summary of changes**
Pushed the "simplified proposal" to this PR as it is the current primary version. In comparison with the 2019-09-10 version, it includes the following updates:
- In the dynamic process creation, require the user to do not use OpenSHMEM communication on dynamically created processes
- In the RMA section, require the user to do not use OpenSHMEM and MPI RMA in the same program.
- Add new rules in the thread safety section
- Use `shmem_sync_all` instread of `shmem_barrier_all` in the example of mapping process identiﬁcation numbers (section 1.4.1)
- Text adjustments.

**Materials for 2019-09-24~2019-09-26 F2F meeting**
- PDF of this PR
[openshmem-spec-interoperability-20190925.pdf](https://github.com/minsii/openshmem-specification/files/3653557/openshmem-spec-interoperability-20190925.pdf)
- Additional discussion slides
[SHMEM_Interoperability_20190926.pptx](https://github.com/minsii/openshmem-specification/files/3658560/SHMEM_Interoperability_20190926.pptx)

**Comment by RaymondMichael** [comment]
I'm not sure that we need to say that applications should avoid MPI Spawn. I believe that the same processes in SHMEM_TEAM_WORLD are the exact same in MPI_COMM_WORLD, albeit with possibly different IDs. Any spawned MPI processes are outside of MPI_COMM_WORLD, and thus OpenSHMEM has no way of addressing them. As long as we all understand this, I don't see a need to say that spawning can't be used.

**Comment by minsii** [comment]
@RaymondMichael Thanks for your feedback. I agree that most implementations may just create the same set of processes for `TEAM_WORLD` and `COMM_WORLD`. However, from specification's view, I do not think the behavior of **OpenSHMEM + MPI spawn (or non-MPI spawn, e.g., fork)** is clear enough. There was a more detailed version of the dynamic process section, which tried to discuss possible scenarios when users use OpenSHMEM + spawn together . It discussed three cases as below:
- case 1:
After MPI initialization and before any PEs start OpenSHMEM initialization, the program spawns a new MPI process. It is unclear whether P1 is included in the original `TEAM_WORLD`. In other words, we have to say it is implementation defined.
```
P0                  Spawned P1
MPI_Init(..)
spawn();
shmem_init();       shmem_init();
```

- case 2:
After MPI and SHMEM initialization, the program spawns a new process and wants to communicate with PEs in the original `TEAM_WORLD`. I think it is clearly no.
```
P0                  Spawned P1
MPI_Init(..)
shmem_init();
spawn();
                    shmem_init();
```

- case 3:
After MPI and SHMEM initialization, the program spawns some new processes. Is there a new `TEAM_WORLD` created for these new processes ? For example, can `P1` and `P2` communicate with each other through OpenSHMEM in the following example ? 
```
P0                  Spawned P1      Spawned P2
MPI_Init(..)
shmem_init();
spawn();
                    shmem_init();   shmem_init();
```

Finally, we found that it is very hard to precisely describe the interoperability of `OpenSHMEM + dynamic process` based on current OpenSHMEM spec. Thus, we think it is better to say that users should not use them together for portability. It allows us to simplify this proposal. We can relax the restriction in future if a user application needs this feature.

Does it make sense to you ?

**Comment by minsii** [comment]
Diff from September F2F meeting: [843d8bb..d560514](https://github.com/minsii/openshmem-specification/compare/843d8bb..d560514)

Summary of changes:
- 1.2 Dynamic Process Creation: delete "MPMD" from the section title
- 1.3 Thread Safety:
  - For the additional thread safety rules, mention them as suggestions to ensure portable hybrid program because they are required only for implementations that provide both OpenSHMEM and MPI.
  - Improve the description of additional rule for `THREAD_SERIALIZED` safety.
- 1.6 Communication Progress:
   - More specific guidance to implementors: use software progress thread if the implementation supports asynchronous communication for both MPI and OpenSHMEM.
   - Add example in `2.1 SHMEM_QUERY_INTEROPERABILITY` to showcase how the progress support can help program to avoid deadlock.
- Others:
  - Example cleanup (header file, unneeded function)
  - Grammar fixes

Performance impact when implementation supports progress for MPI:
- It should only impact on implementations that supports both MPI and OpenSHMEM
- For implementations that already uses a software thread for OpenSHMEM progress, the performance impact should be very small.
- For implementations that provide full hardware progress for OpenSHMEM but has to create a software thread to support MPI progress, performance may be degraded. However, the implementation can optimize it. For example, it can reduce the frequency of thread polling to minimize thread contention&oversubscription overhead. Or it can use other approaches for MPI progress such as Casper: https://github.com/pmodels/casper.
- For implementations that has to involve extra heavy overhead to support MPI progress, it can choose to disable the feature.

Nevertheless, I feel that the optimizations of asynchronous progress is irrelevant to this proposal. Thus, I do not discuss them in detail in the proposal. 

@jdinan @nspark Thanks for all comments at the F2F meeting. Could you please check if all your concerns are addressed?

**Comment by minsii** [comment]
Opened a PR against the main spec repo. Close this PR.

**Pull request closed without merging**
